modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/serechka/HeartsPlus/issues"

[[mods]]
modId = "heartsplus"
version = "${version}"
displayName = "HeartsPlus"
authors = "serechka"
description = '''
Displays player health as vanilla hearts above players' heads. Fully configurable, client-side only.
'''
logoFile = "assets/heartsplus/icon.png"
displayURL = "https://modrinth.com/mod/heartsplus"

[[mixins]]
config = "heartsplus.mixins.json"

[[dependencies.heartsplus]]
modId = "neoforge"
type = "required"
versionRange = "[21.2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.heartsplus]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.2,1.21.4)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.heartsplus]]
modId = "cloth_config"
type = "required"
versionRange = "[16.0.143,)"
ordering = "NONE"
side = "CLIENT"
